theme: minima
title: How to write academic paper using ChatGPT?
author: Weikai Chen
descriptioin: I will teach you how to write abstract and introduction that can be accepted to top-venue conference in 10 minutes
